### ISSUE TITLE
Game quits when you lose

### ISSUE THREAD

**Issue by MattMuelot** [fethicod/Washing_Machine_Thrower#1]
When you get hit by an alien, you lose and the game shuts down. Make a main menu perhaps that you return to when you lose

**Comment by fethicod** [comment]
Hi i know this issue but i didnt add restart when player loose because that might be confusing for some people when try to understand my code they can easily implement this to my code and they can learn how to do that :)

**Comment by fethicod** [comment]
also thanks for adding sounds menu etc ;)
